base: power: domain_governor: Remove unused variable 'now'
Fix the following build warning treated as error:
  drivers/base/power/domain_governor.c:258:10: error: unused variable 'now'

The variable 'now' was declared but never used in cpu_power_down_ok().
Remove it to fix the build with -Werror.